/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ex_4_3

import java.math.BigInteger

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun fib(x: Int): BigInteger {
    tailrec
    fun fib(val1: BigInteger, val2: BigInteger, x: BigInteger): BigInteger =
        when {
            (x == BigInteger.ZERO) -> BigInteger.ONE
            (x == BigInteger.ONE) -> val1 + val2
            else -> fib(val2, val1 + val2, x - BigInteger.ONE)
        }
    return fib(BigInteger.ZERO, BigInteger.ONE, BigInteger.valueOf(x.toLong()))
}


fun main() {
    println(App().greeting)
	println(fib(10))
}
