/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ex_4_3

import java.math.BigInteger

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun fib(n: Int): BigInteger {
    tailrec
    fun fib(nMinus1: BigInteger, nMinus2:BigInteger, n: BigInteger): BigInteger =
        when {
            (n == BigInteger.ZERO) -> BigInteger.ONE
            (n == BigInteger.ONE) -> nMinus1 + nMinus2
            else -> fib(nMinus1+nMinus2, nMinus1, n - BigInteger.ONE)
        }
    return fib(BigInteger.ONE, BigInteger.ZERO, BigInteger.valueOf(n.toLong()))
}


fun main() {
    println(App().greeting)
	println(fib(10))
}
